apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ai-app-skr
    azure.workload.identity/use: "true"
  name: ai-app-skr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-app-skr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-app-skr
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: sa-ai-app
      containers:
      - envFrom:
        - configMapRef:
            name: cm-ai-app-skr
        image: amlragwks.azurecr.io/confidential-ai-app:skr-small-0.6
        volumeMounts:
        - mountPath: /sys/kernel/security
          name: tcg
        - mountPath: /dev/tpmrm0
          name: tpmrm0
        imagePullPolicy: Always
        name: ai-app-skr
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: "4"
            memory: 16Gi
        securityContext:
          privileged: true
      nodeSelector:
        agentpool: cvmnp
      volumes:
      - name: tcg
        hostPath:
          path: /sys/kernel/security
      - name: tpmrm0
        hostPath:
          path: /dev/tpmrm0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ai-app-skr
  name: svc-ai-app-skr
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: ai-app-skr
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: ing-ai-app-skr
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - ai-app-skr.aks-lab.com
    secretName: ingress-cert
  rules:
  - host: "ai-app-skr.aks-lab.com"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: svc-ai-app-skr
            port:
              number: 80
